# -*- coding: utf-8 -*-
"""Telegram Expense Bot (v.1.3.3)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CPrvXSa07WUHzSbSLoleKw0YdcsMBsCB
"""

import telebot
from telebot import types
import gspread
import os
import json
from io import StringIO
from oauth2client.service_account import ServiceAccountCredentials
from datetime import datetime

# === НАСТРОЙКИ ===
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
SPREADSHEET_ID = os.getenv("SPREADSHEET_ID")
GOOGLE_CREDENTIALS = os.getenv("GOOGLE_CREDENTIALS")

# Авторизация в Google Sheets через переменную среды GOOGLE_CREDENTIALS
scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
creds_dict = json.load(StringIO(GOOGLE_CREDENTIALS))
creds = ServiceAccountCredentials.from_json_keyfile_dict(creds_dict, scope)
client = gspread.authorize(creds)

sheet = client.open_by_key(SPREADSHEET_ID)
data_sheet = sheet.worksheet("Данные")
cat_sheet = sheet.worksheet("Категории")

bot = telebot.TeleBot(TELEGRAM_TOKEN)
user_state = {}

BASE_CATEGORIES = {
    "Еда": ["Продукты", "Кафе"],
    "Проезд": ["Метро", "Такси"],
    "Связь": ["Мобильный", "Интернет"],
    "Оплата КУ": ["Электричество", "Вода", "Газ"],
    "Развлечения": ["Кино", "Игры", "Отдых"]
}

def initialize_categories():
    existing = cat_sheet.get_all_values()
    if len(existing) <= 1:
        for cat, subs in BASE_CATEGORIES.items():
            for sub in subs:
                cat_sheet.append_row([cat, sub])

initialize_categories()

@bot.message_handler(commands=["start", "help"])
def send_welcome(message):
    markup = types.ReplyKeyboardMarkup(resize_keyboard=True, row_width=2)
    markup.add(
        types.KeyboardButton("💸 Расход"),
        types.KeyboardButton("💰 Доход"),
        types.KeyboardButton("📂 Категории"),
        types.KeyboardButton("📊 Отчёт"),
        types.KeyboardButton("⚙ Управление")
    )
    bot.send_message(
        message.chat.id,
        "Привет! Я бот для учёта расходов и доходов.\nВыберите действие кнопками или используйте команды:\n/расход — внести расход\n/доход — внести доход\n/категории — список категорий\n/переименовать — переименование\n/удалить — удалить\n/отчёт [год-месяц] — отчёт за месяц",
        reply_markup=markup
    )

@bot.message_handler(func=lambda message: message.text in ["💸 Расход", "/расход"])
def start_expense(message):
    start_transaction(message, "расход")

@bot.message_handler(func=lambda message: message.text in ["💰 Доход", "/доход"])
def start_income(message):
    start_transaction(message, "доход")

def start_transaction(message, type_):
    chat_id = message.chat.id
    categories = list(set([row[0] for row in cat_sheet.get_all_values()[1:] if row[0]]))
    markup = types.ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True)
    for cat in categories:
        markup.add(cat)
    markup.add("➕ Новая категория")
    user_state[chat_id] = {"step": "category", "type": type_}
    bot.send_message(chat_id, "Выберите категорию:", reply_markup=markup)

@bot.message_handler(func=lambda m: True)
def handle_text(message):
    chat_id = message.chat.id
    state = user_state.get(chat_id)
    if not state:
        return

    step = state["step"]

    if step == "category":
        if message.text == "➕ Новая категория":
            bot.send_message(chat_id, "Введите название новой категории:")
            state["step"] = "new_category"
        else:
            state["category"] = message.text
            show_subcategories(chat_id, message.text)

    elif step == "new_category":
        category = message.text.strip()
        cat_sheet.append_row([category, ""])
        state["category"] = category
        bot.send_message(chat_id, f"Категория '{category}' добавлена.")
        show_subcategories(chat_id, category)

    elif step == "subcategory":
        if message.text == "➕ Новая подкатегория":
            bot.send_message(chat_id, "Введите название новой подкатегории:")
            state["step"] = "new_subcategory"
        else:
            state["subcategory"] = message.text
            bot.send_message(chat_id, "Введите сумму:")
            state["step"] = "amount"

    elif step == "new_subcategory":
        subcategory = message.text.strip()
        cat_sheet.append_row([state["category"], subcategory])
        state["subcategory"] = subcategory
        bot.send_message(chat_id, f"Подкатегория '{subcategory}' добавлена.\nВведите сумму:")
        state["step"] = "amount"

    elif step == "amount":
        try:
            amount = float(message.text.strip())
            now = datetime.now()
            now_str = now.strftime("%Y-%m-%d %H:%M:%S")
            year = now.strftime("%Y")
            month = now.strftime("%Y-%m")
            user = message.from_user.username or message.from_user.first_name
            data_sheet.append_row([
                now_str,
                year,
                month,
                state.get("type", "расход"),
                amount,
                state["category"],
                state["subcategory"],
                user
            ])
            bot.send_message(chat_id, f"✅ {state['type'].capitalize()} {amount}₽ в категории '{state['category']} / {state['subcategory']}' добавлен.")
        except ValueError:
            bot.send_message(chat_id, "❗ Введите сумму числом, например: 250")
        finally:
            user_state.pop(chat_id, None)

def show_subcategories(chat_id, category):
    rows = cat_sheet.get_all_values()[1:]
    subcategories = [r[1] for r in rows if r[0] == category and r[1]]
    markup = types.ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True)
    for sub in subcategories:
        markup.add(sub)
    markup.add("➕ Новая подкатегория")
    user_state[chat_id]["step"] = "subcategory"
    bot.send_message(chat_id, "Выберите подкатегорию:", reply_markup=markup)

bot.polling()
